export const MAX_PHOTO_BYTES = 5 * 1024 * 1024;
export const PHOTO_TYPES = Object.freeze({ 'image/jpeg': 'jpg', 'image/png': 'png', 'image/webp': 'webp' });
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export class ValidationError extends Error { constructor(message) { super(message); this.name = 'ValidationError'; } }
function invalid(message) { throw new ValidationError(message); }
function object(value, field) { if (!value || typeof value !== 'object' || Array.isArray(value)) invalid(field + ' must be an object.'); return value; }
function text(value, field, max, required = false) { if (value === undefined || value === null) { if (required) invalid(field + ' is required.'); return ''; } if (typeof value !== 'string') invalid(field + ' must be text.'); const result = value.trim(); if (result.length > max || (required && !result)) invalid(field + ' must contain ' + (required ? '1–' : 'at most ') + max + ' characters.'); return result; }
export function validateId(value) { if (typeof value !== 'string' || !UUID.test(value)) invalid('A valid record UUID is required.'); return value; }
export function validatePhotoKey(key, userId) { const prefix = 'users/' + userId + '/'; if (typeof key !== 'string' || !key.startsWith(prefix)) invalid('Photo does not belong to this account.'); const filename = key.slice(prefix.length); const dot = filename.lastIndexOf('.'); if (!UUID.test(filename.slice(0, dot)) || !['jpg','png','webp'].includes(filename.slice(dot + 1))) invalid('Invalid photo key.'); return key; }
export function validateUpload(input) { object(input, 'Upload'); const name = text(input.name, 'File name', 180, true); if (!Object.hasOwn(PHOTO_TYPES, input.mimeType)) invalid('Choose a JPEG, PNG, or WebP photo.'); if (!Number.isInteger(input.sizeBytes) || input.sizeBytes < 1 || input.sizeBytes > MAX_PHOTO_BYTES) invalid('Photo must be between 1 byte and 5 MiB.'); return { name, mimeType: input.mimeType, sizeBytes: input.sizeBytes }; }
export function validateRecord(input, id, userId) {
  object(input, 'Record'); validateId(id); if (input.id !== undefined && input.id !== id) invalid('Record ID does not match its URL.');
  if (typeof input.date !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(input.date) || !Number.isFinite(Date.parse(input.date + 'T00:00:00Z')) || new Date(input.date + 'T00:00:00Z').toISOString().slice(0, 10) !== input.date) invalid('Choose a real calendar date.');
  if (typeof input.wasteKg !== 'number' || !Number.isFinite(input.wasteKg) || input.wasteKg < 0 || input.wasteKg > 100000) invalid('Waste must be a number from 0 to 100,000 kg.');
  if (!['plate','kitchen','combined','unknown'].includes(input.scope)) invalid('Choose a valid waste scope.');
  const menu = object(input.menu, 'Menu');
  const result = { id, date: input.date, wasteKg: input.wasteKg, scope: input.scope, coverage: text(input.coverage, 'Meal coverage', 100, true), menu: {breakfast: text(menu.breakfast, 'Breakfast', 1000), lunch: text(menu.lunch, 'Lunch', 1000), dinner: text(menu.dinner, 'Dinner', 1000)}, notes: text(input.notes, 'Notes', 3000), photos: [] };
  if (input.attendance !== undefined && input.attendance !== null) { if (!Number.isInteger(input.attendance) || input.attendance < 1 || input.attendance > 1000000) invalid('Meals served must be a whole number from 1 to 1,000,000.'); result.attendance = input.attendance; }
  if (input.photos !== undefined) { if (!Array.isArray(input.photos) || input.photos.length > 6) invalid('Attach at most six photos per record.'); result.photos = input.photos.map((photo) => { object(photo, 'Photo'); validateId(photo.id); if (!['board','plate'].includes(photo.kind)) invalid('Photo must show the board or a plate.'); if (photo.url) invalid('Upload photos to private storage before saving.'); const key = validatePhotoKey(photo.key, userId); if (!Object.hasOwn(PHOTO_TYPES, photo.mimeType)) invalid('Photo type must be JPEG, PNG, or WebP.'); if (!key.endsWith('.' + PHOTO_TYPES[photo.mimeType])) invalid('Photo key and type do not match.'); return { id: photo.id, name: text(photo.name, 'Photo name', 180, true), kind: photo.kind, key, mimeType: photo.mimeType }; }); if (new Set(result.photos.map(p => p.id)).size !== result.photos.length) invalid('Photo IDs must be unique.'); }
  if (input.action !== undefined && input.action !== null) { object(input.action, 'Action'); if (!['planned','in_progress','completed'].includes(input.action.status)) invalid('Choose a valid action status.'); result.action = {text: text(input.action.text, 'Action', 1000, true), status: input.action.status, notes: text(input.action.notes, 'Action notes', 2000)}; }
  return result;
}
